version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-load-balancer/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  keycloak1:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak_1
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_PROXY=edge
      - KC_HOSTNAME=your_domain.com
    ports:
      - "8180:8080"
    restart: unless-stopped

  keycloak2:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak_2
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_PROXY=edge
      - KC_HOSTNAME=your_domain.com
    ports:
      - "8280:8080"
    restart: unless-stopped
  
  # Cấu hình cho Kong và cơ sở dữ liệu của nó
  # ... (Bạn cần thêm cấu hình cho các instance Kong và database tương ứng)
  # Ví dụ cho một cặp Kong và Postgres:

  kong-db-1:
    image: postgres:13
    container_name: kong_db_1
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    restart: unless-stopped

  kong-migration-1:
    image: kong:latest
    command: "kong migrations bootstrap"
    depends_on:
      - kong-db-1
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db-1
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    restart: on-failure

  kong1:
    image: kong:latest
    container_name: kong_1
    depends_on:
      - kong-migration-1
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db-1
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    restart: unless-stopped

  # Cấu hình cho instance Kong thứ hai
  kong-db-2:
    image: postgres:13
    container_name: kong_db_2
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    restart: unless-stopped

  kong-migration-2:
    image: kong:latest
    command: "kong migrations bootstrap"
    depends_on:
      - kong-db-2
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db-2
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    restart: on-failure

  kong2:
    image: kong:latest
    container_name: kong_2
    depends_on:
      - kong-migration-2
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db-2
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      # Ánh xạ cổng proxy của instance 2 ra một cổng khác trên host
      - "8002:8000"
      - "8445:8443"
      # Cổng admin có thể giữ nguyên nếu bạn cấu hình từng cái một
      # Hoặc ánh xạ ra cổng khác nếu muốn truy cập đồng thời
      - "8003:8001"
      - "8446:8444"
    restart: unless-stopped

networks:
  default:
    driver: bridge 